apiVersion: v1
kind: Service
metadata:
  name: rule
spec:
  type: NodePort
  ports:
    - port: 3001
  selector:
    app: rule
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2，after 1.9.0 use apps/v1
kind: Deployment
metadata:
  name: rule
spec:
  selector:
    matchLabels:
      app: rule
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rule
    spec:
      containers:
        - image: registry.cn-shanghai.aliyuncs.com/jike-serverless/rule:latest
          name: rule
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: "3001"
          ports:
            - containerPort: 3001
              name: rule
      imagePullSecrets:
        - name: regcred

#apiVersion: v1
#kind: Pod
#metadata:
#  name: myapp
#spec:
#  containers:
#    - name: myapp
#      image: registry.cn-shanghai.aliyuncs.com/jike-serverless/todolist:latest
#  imagePullSecrets:
#    - name: regcred
